jobs:
    main:
        requires: [ ~pr, ~commit ]
        image: node:14
        steps:
            - install: npm install
            - test: npm test

    tag-triggered:
        requires: [ ~tag ]
        image: node:14
        steps:
            - test: |
                    tag_name=$(meta get sd.tag.name)
                    echo "${tag_name}"

                    if [ "$tag_name" != "v1.0" ] && [ "$tag_name" != "v2.0" ]; then
                        echo 'The metadata sd.tag.name should be set.'
                        exit 1
                    fi

    release-triggered:
        requires: [ ~release ]
        image: node:14
        steps:
            - test: |
                    release_name=$(meta get sd.release.name)
                    release_id=$(meta get sd.release.id)
                    release_author=$(meta get sd.release.author)
                    echo "${release_id}, ${release_name}, ${release_author}"

                    if [ "$release_name" != "v1.0" ] && [ "$release_name" != "v2.0" ]; then
                        echo 'The metadata sd.release.name should be set.'
                        exit 1
                    fi
                    if [ "$release_id" = "null" ]; then
                        echo 'The metadata sd.release.id should be set.'
                        exit 1
                    fi
                    if [ "$release_author" = "null" ]; then
                        echo 'The metadata sd.release.author should be set.'
                        exit 1
                    fi

    tag-specific-triggered:
        requires: [ ~tag:/^v1\..*/ ]
        image: node:14
        steps:
            - echo: echo test
        annotations:
            screwdriver.cd/virtualJob: true

    release-specific-triggered:
        requires: [ ~release:v1.0 ]
        image: node:14
        steps:
            - echo: echo test
        annotations:
            screwdriver.cd/virtualJob: true

    closed-trigger:
        requires: [ ~pr-closed ]
        image: node:14
        steps:
            - echo: echo test
        annotations:
            screwdriver.cd/virtualJob: true

    branch-specific-closed-trigger:
        requires: [ ~pr-closed:pr-closed-trigger ]
        image: node:14
        steps:
            - test: |
                    prName=$(meta get sd.pr.name)
                    prMerged=$(meta get sd.pr.merged)
                    prNumber=$(meta get sd.pr.number)

                    echo "${prName} - ${prMerged} - ${prNumber}"

                    if [ -z "$prName" ]; then
                        echo 'The metadata sd.pr.name should be set.'
                        exit 1
                    fi
                    if [ "$prMerged" != "true" ]; then
                        echo 'The metadata sd.pr.merged should be true.'
                        exit 1
                    fi
                    if [ -z "$prNumber" ]; then
                        echo 'The metadata sd.pr.number should be set.'
                        exit 1
                    fi
