jobs:
    main:
        requires: [ ~pr, ~commit ]
        image: node:10
        steps:
            - install: npm install
            - test: npm test

    tag-triggered:
        requires: [ ~tag ]
        image: node:10
        steps:
            - install: npm install
            - test: npm test

    release-triggered:
        requires: [ ~release ]
        image: node:10
        steps:
            - install: npm install
            - test: npm test
